[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
outcome = "9tEramtR21bLBHvXqa4sofVBPa1ZBho4WzhCkCimFE1F"

[programs.devnet]
outcome = "9tEramtR21bLBHvXqa4sofVBPa1ZBho4WzhCkCimFE1F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p outcome"
