[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
outcome = "3b7TFKQWUhPqWBieLHop4Mj2e41vwvnvjEosbsdmXkBq"

[programs.devnet]
outcome = "3b7TFKQWUhPqWBieLHop4Mj2e41vwvnvjEosbsdmXkBq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p outcome"
